name: Squid Base Image CI

on:
  push:
    branches:
      - master

jobs:
  generate_version_information:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      latest_version: ${{ steps.set-latest.outputs.latest_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Generate matrix dynamically
        id: set-matrix
        run: |
          # Find all numerical subdirectories in the squid directory
          matrix=$(find squid -mindepth 1 -maxdepth 1 -type d -exec basename {} \; | grep -E '^[0-9]+$' | jq -R . | jq -s .)
          echo "Matrix: $matrix"
          echo "::set-output name=matrix::$matrix"
      - name: Determine latest version
        id: set-latest
        run: |
          # Find the highest numerical subdirectory
          latest_version=$(find squid -mindepth 1 -maxdepth 1 -type d -exec basename {} \; | grep -E '^[0-9]+$' | sort -n | tail -1)
          echo "Latest version: $latest_version"
          echo "::set-output name=latest_version::$latest_version"
  build_and_publish:
    needs: generate_version_information
    runs-on: ubuntu-latest
    strategy:
      matrix:
        squid_version: ${{ fromJson(needs.generate_version_information.outputs.matrix) }}
    env:
      LATEST_VERSION: ${{ needs.generate_version_information.outputs.latest_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Generate timestamp
        id: timestamp
        run: |
          # Generate a timestamp in the format YYYYMMDD-HHMMSS
          timestamp=$(date -u +"%Y%m%d-%H%M%S")
          echo "Timestamp: $timestamp"
          echo "::set-output name=timestamp::$timestamp"
      - name: Build and push Docker image (Squid ${{ matrix.squid_version }})
        uses: docker/build-push-action@v6
        with:
          context: ./squid/${{ matrix.squid_version }}
          file: ./squid/${{ matrix.squid_version }}/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/squid:${{ matrix.squid_version }}
            ghcr.io/${{ github.repository_owner }}/squid:${{ env.LATEST_VERSION == matrix.squid_version && 'latest' || '' }}
            ghcr.io/${{ github.repository_owner }}/squid:${{ matrix.squid_version }}-${{ steps.timestamp.outputs.timestamp }}
