name: Squid Base Image CI

on:
  push:
    branches:
      - master

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker image (Squid 5)
        uses: docker/build-push-action@v6
        with:
          context: ./squid/5
          file: ./squid/5/Dockerfile
          push: true
          tags: ghcr.io/brooks630/squid:5
      - name: Build and push Docker image (Squid 6)
        uses: docker/build-push-action@v6
        with:
          context: ./squid/6
          file: ./squid/6/Dockerfile
          push: true
          tags: ghcr.io/brooks630/squid:6
